"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

const NAVY = "#071B34";
const ORANGE = "#F97316";
const money = (value) => `₹${Number(value || 0).toFixed(2)}`;

function syncCustomerLedger(customer) {
  const bookings = JSON.parse(window.localStorage.getItem("agc_bookings") || "[]"); const existing = JSON.parse(window.localStorage.getItem("agc_ledger") || "[]"); const entries = [...existing];
  bookings.filter((booking) => booking.consignor?.name?.toLowerCase() === customer.name.toLowerCase() && booking.paymentType !== "paid").forEach((booking) => { if (!entries.some((entry) => entry.lrNumber === booking.lrNumber && entry.type === "debit")) entries.push({ id: `LEDGER-${booking.lrNumber}`, customerId: customer.id, customerName: customer.name, mobile: customer.mobile, lrNumber: booking.lrNumber, date: booking.date || booking.createdAt?.slice(0, 10), particular: booking.paymentType === "tbb" ? "TBB Receivable" : "To Pay Booking", debit: Number(booking.grandTotal || 0), credit: 0, type: "debit", createdAt: new Date().toISOString() }); }); window.localStorage.setItem("agc_ledger", JSON.stringify(entries)); return entries;
}

export default function CustomerLedgerPage() {
  const params = useParams(); const [customer, setCustomer] = useState(null); const [entries, setEntries] = useState([]);
  useEffect(() => { const customers = JSON.parse(window.localStorage.getItem("agc_customers") || "[]"); const record = customers.find((item) => item.id === decodeURIComponent(params?.customerId || "")); if (record) { const ledger = syncCustomerLedger(record); setCustomer(record); setEntries(ledger.filter((entry) => entry.customerId === record.id)); } }, [params]);
  if (!customer) return <main className="flex min-h-screen items-center justify-center bg-slate-50"><div className="rounded-2xl bg-white p-8 text-center"><h1 className="text-xl font-bold" style={{ color: NAVY }}>Customer not found</h1><a href="/accounts" className="mt-4 inline-block text-orange-600">Back to Accounts</a></div></main>;
  const ordered = [...entries].sort((a, b) => String(b.date).localeCompare(String(a.date))); let running = 0; const rows = [...ordered].reverse().map((entry) => { running += Number(entry.debit || 0) - Number(entry.credit || 0); return { ...entry, balance: running }; }).reverse(); const debit = entries.reduce((total, entry) => total + Number(entry.debit || 0), 0); const credit = entries.reduce((total, entry) => total + Number(entry.credit || 0), 0);
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><div className="mb-6 flex items-end justify-between"><div><a href="/accounts" className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Accounts / Ledger</a><h1 className="mt-2 text-3xl font-bold" style={{ color: NAVY }}>{customer.name}</h1><p className="mt-1 text-sm text-slate-500">{customer.id} · {customer.mobile} · {customer.gst || "GST not available"}</p></div><div className="flex gap-2"><a href={`/accounts/payment?customerId=${customer.id}`} className="rounded-lg px-4 py-2 text-sm font-semibold text-white" style={{ backgroundColor: ORANGE }}>Receive Payment</a><button onClick={() => window.print()} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Print Ledger</button><button onClick={() => window.alert("PDF export is reserved for the next workflow step.")} className="rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700">Export PDF</button></div></div><div className="grid gap-3 sm:grid-cols-3">{[["Total Debit", money(debit)], ["Total Credit", money(credit)], ["Outstanding Balance", money(debit - credit)]].map(([label, value]) => <section key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[0.1em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold" style={{ color: NAVY }}>{value}</p></section>)}</div><div className="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><table className="min-w-full divide-y divide-slate-100"><thead className="bg-slate-50"><tr>{["Date", "LR", "Particular", "Debit", "Credit", "Balance"].map((heading) => <th key={heading} className="px-5 py-3 text-left text-[11px] font-bold uppercase tracking-[0.1em] text-slate-500">{heading}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.length ? rows.map((entry) => <tr key={entry.id}><td className="px-5 py-4 text-sm">{entry.date || "-"}</td><td className="px-5 py-4 text-sm font-bold">{entry.lrNumber || "-"}</td><td className="px-5 py-4 text-sm">{entry.particular}</td><td className="px-5 py-4 text-sm">{money(entry.debit)}</td><td className="px-5 py-4 text-sm">{money(entry.credit)}</td><td className="px-5 py-4 text-sm font-bold" style={{ color: entry.balance > 0 ? ORANGE : "#15803d" }}>{money(entry.balance)}</td></tr>) : <tr><td colSpan="6" className="px-5 py-20 text-center text-sm text-slate-500">No ledger transactions found.</td></tr>}</tbody></table></div></div></main>;
}
