"use client";

import { useState } from "react";

const NAVY = "#071B34";
const ORANGE = "#F97316";
const initialForm = { truckNumber: "", vehicleType: "", capacity: "", route: "", driverName: "", driverMobile: "", licenseNumber: "", insuranceExpiry: "", fitnessExpiry: "", permitExpiry: "", pollutionExpiry: "", status: "Active" };
const input = "h-[42px] w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-orange-300 focus:bg-white focus:ring-2 focus:ring-orange-100";

export default function NewVehiclePage() {
  const [form, setForm] = useState(initialForm); const [error, setError] = useState("");
  const update = (field) => (event) => setForm((previous) => ({ ...previous, [field]: field === "driverMobile" ? event.target.value.replace(/\D/g, "").slice(0, 10) : event.target.value }));
  const save = (event) => { event.preventDefault(); const vehicles = JSON.parse(window.localStorage.getItem("agc_vehicles") || "[]"); if (!form.truckNumber.trim()) { setError("Truck Number is required."); return; } if (vehicles.some((vehicle) => vehicle.truckNumber.toLowerCase() === form.truckNumber.trim().toLowerCase())) { setError("Truck Number must be unique."); return; } const next = vehicles.reduce((max, vehicle) => Math.max(max, Number(String(vehicle.id).replace("VEH", "")) || 0), 0) + 1; const vehicle = { ...form, truckNumber: form.truckNumber.trim().toUpperCase(), id: `VEH${String(next).padStart(4, "0")}`, createdAt: new Date().toISOString() }; window.localStorage.setItem("agc_vehicles", JSON.stringify([...vehicles, vehicle])); window.location.href = `/vehicles/${vehicle.id}`; };
  const fields = [["Truck Number", "truckNumber"], ["Vehicle Type", "vehicleType"], ["Capacity", "capacity"], ["Route", "route"], ["Driver Name", "driverName"], ["Driver Mobile", "driverMobile"], ["License Number", "licenseNumber"], ["Insurance Expiry", "insuranceExpiry"], ["Fitness Expiry", "fitnessExpiry"], ["Permit Expiry", "permitExpiry"], ["Pollution Expiry", "pollutionExpiry"]];
  return <main className="min-h-screen bg-slate-50 px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><div className="mb-6"><a href="/vehicles" className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Vehicle Master / New</a><h1 className="mt-2 text-3xl font-bold" style={{ color: NAVY }}>Add Vehicle</h1></div><form onSubmit={save} className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-sm font-bold uppercase tracking-[0.12em]" style={{ color: NAVY }}>Vehicle &amp; Driver</h2><div className="grid gap-4 sm:grid-cols-2">{fields.slice(0, 7).map(([label, field]) => <label key={field} className="text-xs font-semibold text-slate-700">{label}{field === "truckNumber" && " *"}<input required={field === "truckNumber"} className={`${input} mt-1.5`} value={form[field]} onChange={update(field)} /></label>)}</div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="mb-4 text-sm font-bold uppercase tracking-[0.12em]" style={{ color: NAVY }}>Documents</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{fields.slice(7).map(([label, field]) => <label key={field} className="text-xs font-semibold text-slate-700">{label}<input type="date" className={`${input} mt-1.5`} value={form[field]} onChange={update(field)} /></label>)}</div></section>{error && <p className="rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button type="button" onClick={() => setForm(initialForm)} className="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-slate-700">Reset</button><button className="rounded-xl px-5 py-2.5 text-sm font-semibold text-white" style={{ backgroundColor: ORANGE }}>Save Vehicle</button></div></form></div></main>;
}
